const { withDangerousMod } = require('@expo/config-plugins')
const fs = require('fs')
const path = require('path')

function buildFactoryKt(packageName, notification) {
  const title = JSON.stringify(notification.title)
  const text = JSON.stringify(notification.text)
  const channelId = JSON.stringify(notification.channelId)
  const channelName = JSON.stringify(notification.channelName)
  const smallIconExpr = notification.iconResource
    ? `R.drawable.${notification.iconResource}`
    : `context.applicationInfo.icon`

  return `package ${packageName}

import android.app.Notification
import android.app.NotificationChannel
import android.app.NotificationManager
import android.content.Context
import android.os.Build
import androidx.core.app.NotificationCompat

// Generated by the react-native-motiontag Expo config plugin.
// Edit options in app.json (motiontag plugin) and re-run \`expo prebuild\`.
object MotionTagNotificationFactory {

  private const val CHANNEL_ID = ${channelId}
  private const val CHANNEL_NAME = ${channelName}
  private const val TITLE = ${title}
  private const val TEXT = ${text}

  @JvmStatic
  fun create(context: Context): Notification {
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
      val channel = NotificationChannel(
        CHANNEL_ID,
        CHANNEL_NAME,
        NotificationManager.IMPORTANCE_LOW
      )
      val manager = context.getSystemService(NotificationManager::class.java)
      manager.createNotificationChannel(channel)
    }

    return NotificationCompat.Builder(context, CHANNEL_ID)
      .setContentTitle(TITLE)
      .setContentText(TEXT)
      .setSmallIcon(${smallIconExpr})
      .setOngoing(true)
      .setPriority(NotificationCompat.PRIORITY_LOW)
      .build()
  }
}
`
}

module.exports = function withAndroidNotification(config, notification) {
  return withDangerousMod(config, [
    'android',
    async (cfg) => {
      const pkg = cfg.android && cfg.android.package
      if (!pkg) {
        throw new Error(
          '[react-native-motiontag] android.package must be set in app.json before this plugin runs.',
        )
      }
      const pkgPath = pkg.replace(/\./g, '/')
      const dir = path.join(
        cfg.modRequest.platformProjectRoot,
        'app',
        'src',
        'main',
        'java',
        pkgPath,
      )
      fs.mkdirSync(dir, { recursive: true })
      const file = path.join(dir, 'MotionTagNotificationFactory.kt')
      fs.writeFileSync(file, buildFactoryKt(pkg, notification))
      return cfg
    },
  ])
}
